openapi: 3.1.0
info:
  title: Laundry Status API
  version: 1.0.0
  description: API for querying the status of laundry machines in dormitories.
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /api
tags:
  - name: Dorms
    description: Operations related to dormitories.
  - name: Machines
    description: Operations related to laundry machines.
paths:
  /dorms:
    $ref: './paths/dorms.yaml'
  /dorms/{dorm_id}/machines:
    $ref: './paths/machines.yaml'
components:
  schemas:
    Dorm:
      $ref: './components/schemas/dorm.yaml'
    Machine:
      $ref: './components/schemas/machine.yaml'
    Error:
      $ref: './components/schemas/error.yaml'
  parameters:
    DormID:
      $ref: './components/parameters/dorm_id.yaml'
    AtTimestamp:
      $ref: './components/parameters/at_timestamp.yaml'