version: "3.8"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=laundry
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d laundry"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports: ["8080:8080"]
    volumes:
      - .:/app
      - ./config/config.yaml:/app/config.yaml